### ISSUE TITLE
No module named '_curses

### ISSUE THREAD

**Issue by forsomefun** [beaston02/MFCRecorder#13]
I using windows and this module can't be installed. 

From a quick search, it looks like they might not be a windows version of this.

**Comment by beaston02** [comment]
When are you getting this error? I cant recall using a module named "_curses". 

have you by chance installed the requirements using pip, and tried running it? I assume youre getting this error when running pip. Also, you are using python3.5+, correct?

**Comment by forsomefun** [comment]
WIth the new version added 18 hours ago
This is the output
D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py
Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 1, in <module>
    import time, datetime, os, threading, sys, configparser, subprocess, blessings, pickle
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python35-32\lib\site-packages\blessings\__init__.py", line 5, in <module>
    import curses
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python35-32\lib\curses\__init__.py", line 13, in <module>
    from _curses import *
ImportError: No module named '_curses'

**Comment by forsomefun** [comment]
Yes it was working until I updated the program today
So I'm, sure my python program is up to date

**Comment by beaston02** [comment]
ok. Thanks. I just added blessings, which from the error seems to be whats causing the trouble. 

Let me see if I cant sort this out. I dont have a windows machine to test on, but Ill see if I cant find a proper solution through google. 

Thank you for reporting the issue!

**Comment by forsomefun** [comment]
Actually, I solved the first problem with this package here 
http://www.lfd.uci.edu/~gohlke/pythonlibs/#curses

I don't know how to code. So this is getting very confusing.

**Comment by beaston02** [comment]
Lol. Great job. 

I still consider myself to be a beginner to python, so hopefully between the two of us we can tackle this ;) 

You mention you solved the "first problem", what problem/error are you having now, or is it the same error as before?

**Comment by forsomefun** [comment]
D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py
Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 1, in <module>
    import time, datetime, os, threading, sys, configparser, subprocess, blessings, pickle
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python35-32\lib\site-packages\blessings\__init__.py", line 7, in <module>
    from fcntl import ioctl
ImportError: No module named 'fcntl' 

Then when I go to 
C:\Users\tobif\AppData\Local\Programs\Python\Python35-32\Scripts 
and run
pip install fcntl 
which how I've installed every other module

I get error

 pip install fcntl
Collecting fcntl
  Could not find a version that satisfies the requirement fcntl (from versions: )
No matching distribution found for fcntl

So I looked to see if their is a manual package I can install. But I haven't seen one yet

**Comment by beaston02** [comment]
Thanks again. 

Blessings (which is causing the problem) is there to simply clean up the output of logging in terminal some. The last changes I made really mucked up the output and blessings was a workaround to keep it looking neat. I can remove it and the script will still function fine, it will just be very sloppy output until I can put together something better

**Comment by beaston02** [comment]
I just made some changes to only use blessings if it is not a windows system. As I mentioned, the output will be very sloppy, but it should otherwise work fine. Im working on a better display of the info/statistics, so I dont want to spend much time fixing this when its just going to be replaced. 

Please make sure to update mfcauto as I also made changes to it to work with windows (command is in the readme)

Again, I dont have windows to test this on, so please let me know if you have problems.

**Comment by forsomefun** [comment]
Getting this error
 D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py
Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 193, in <module>
    getOnlineModels()
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 85, in getOnlineModels
    with open(wishlist) as f:
OSError: [Errno 22] Invalid argument: 'wishlist = D:\\Lockbox\\Others\\MFCRecorder-master\\wanted.txt'

Trying to see if I made any mistakes in installation, but I don't think so

**Comment by beaston02** [comment]
Could you change line 85 in MFCRecorder.py from 
`with open(wishlist) as f:`
to
`with open(wishlist,"r") as f:`
and let me know if that fixes it?

**Comment by forsomefun** [comment]
D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py
Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master/getModels.py", line 2, in <module>
    from mfcauto import Client, Model, FCTYPE, STATE
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\__init__.py", line 2, in <module>
    from .client import Client, SimpleClient
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\site-packages\mfcauto\client.py", line 20, in <module>
    from async_timeout import timeout
ModuleNotFoundError: No module named 'async_timeout'
Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 193, in <module>
    getOnlineModels()
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 110, in getOnlineModels
    with open('models.pickle', 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'models.pickle'

**Comment by beaston02** [comment]
lol. Sorry about all the trouble! 

I forgot I added timeouts to the mfcauto. I just updated it removing the timeouts (they were for testing, and not being used now) 

Could you update it again (command in the readme) and see if it works?

**Comment by forsomefun** [comment]
It almost their I think 
Maybe something need to be changed here 
models.pickle
====================

____________________Connection Status____________________
Connecting to MyFreeCams chat server ychat30...
Login handshake completed. Logged in as 'Guest95259' with sessionId 296015349
Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master/getModels.py", line 69, in <module>
    getOnlineModels()
  File "D:\Lockbox\Others\MFCRecorder-master/getModels.py", line 56, in getOnlineModels
    with open('models.pickle', 'wb') as handle:
PermissionError: [Errno 13] Permission denied: 'models.pickle'
Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 193, in <module>
    getOnlineModels()
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 110, in getOnlineModels
    with open('models.pickle', 'rb') as handle:
FileNotFoundError: [Errno 2] No such file or directory: 'models.pickle'

**Comment by forsomefun** [comment]
actually the program seems to be running when I click on it directly 
instead of using cmder like I usually do. 
So it seems like the issue is fixed on your end. 

I want to check if it will record though. WIll edit with results

**Comment by beaston02** [comment]
getting closer!! haha

`File "D:\Lockbox\Others\MFCRecorder-master/getModels.py", line 56, in getOnlineModels
with open('models.pickle', 'wb') as handle:
PermissionError: [Errno 13] Permission denied: 'models.pickle'`

What the script does (changed yesterday addressing the hanging on connection issue which has plagued this script since day 1) is it runs the script getModels.py to get the online models (this way, if it hangs it can kill that process and try again). That model writes the data to a file called 'models.pickle' as your seeing in the error. The portion I quoted above is saying you do not have permission to write the file, which would be a permission for that directory (this is the same directory containing the MFCRecorder.py file, in your case it seems to be "D:\Lockbox\Others\MFCRecorder-master/"). 

Im not familiar with Windows OS, but this seems like an odd problem since, I imagine, youre able to download the files to that directory but not letting the script save to the same directory. 

If this was linux, I would say chmod the directory adding your user/group to have write permissions, but I do not know how this is handled in windows. 

You just posted another reply which seems to confirm this issue. Unfortunately, I do not know how to handle this in windows. It seems it is ran as a different user when ran from cmder. I would suggest googling for a solution, or change the permissions of the directory (D:\Lockbox\Others\MFCRecorder-master/) to allow non owners (or whatever it is) to have write access.

**Comment by forsomefun** [comment]
I don't no if you saw my new update. 
But I got it to run with a different cmd program. 

Not sure if this is how it is meant to output
2 model(s) are being recorded. Next check in 20 seconds
Exception in thread Thread-2:g recorded: ['CoraBorealis', 'KatieBelle']
Traceback (most recent call last):
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 134, in startRecording
    month=now.strftime("%m"), year=now.strftime("%Y"), auto=model['condition']) ValueError: unexpected '{' in field name

Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "C:\Users\tobif\AppData\Local\Programs\Python\Python36-32\lib\threading.py", line 864, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Lockbox\Others\MFCRecorder-master\MFCRecorder.py", line 134, in startRecording
    month=now.strftime("%m"), year=now.strftime("%Y"), auto=model['condition']) ValueError: unexpected '{' in field name

0 model(s) are being recorded. Next check in 19 seconds
0 model(s) are being recorded. Next check in 18 seconds
0 model(s) are being recorded. Next check in 17 seconds
0 model(s) are being recorded. Next check in 16 seconds
0 model(s) are being recorded. Next check in 15 seconds
0 model(s) are being recorded. Next check in 14 seconds
0 model(s) are being recorded. Next check in 13 seconds
0 model(s) are being recorded. Next check in 12 seconds
0 model(s) are being recorded. Next check in 11 seconds
0 model(s) are being recorded. Next check in 10 seconds
0 model(s) are being recorded. Next check in 9 seconds
0 model(s) are being recorded. Next check in 8 seconds
0 model(s) are being recorded. Next check in 7 seconds
0 model(s) are being recorded. Next check in 6 seconds
0 model(s) are being recorded. Next check in 5 seconds
0 model(s) are being recorded. Next check in 4 seconds
0 model(s) are being recorded. Next check in 3 seconds
0 model(s) are being recorded. Next check in 2 seconds

**Comment by beaston02** [comment]
I did see your previous update. It popped up while I was typing my last response

This new error is odd. Could you add a line after line 121 in MFCRecorder.py (which is "def startRecording(model):")

add "print(model)" there and could you post the output after doing that? Im wondering if its formatting the json data incorrectly and including a "{" for some reason. 

so line 121 will be: "def startRecording(model):"
line122 will be: "print(model)"
and line 123 will be: "try:"
(all without the quotes)

My other thought is if you have the "directory_structure" set correctly in the config.conf file as it uses curly brackets for the variables. 

as far as the non error output, that all seems to be as expected. Its going to be a lot of extra lines and sloppy because of the issue with blessings, and my quick fix of essentially just removing blessings and not handling the output in any other way.

**Comment by forsomefun** [comment]
Sorry I might have made a mistake 
I got it to work let me see if my fix worked though 

I adding a few wrong brackets in the config file. 
However, windows users might need to run the program slightly different. I will update soon

**Comment by beaston02** [comment]
Thank you. 

As you've seen, I make plenty of mistakes, so no worries ;) haha

I appreciate all the input and the patience. Im learning as I go, and not having access to windows makes certain aspects very difficult, so all the help from the windows users is much appreciated!

**Comment by forsomefun** [comment]
Ya we got it 
Last thing. Just going to put it here for other people who read this. 

running the cmd as administrator makes the output a lot cleaner. I think it also makes the program more stable

Otherwise this error comes up


Traceback (most recent call last):
  File "D:\Lockbox\Others\MFCRecorder-master/getModels.py", line 69, in <module>
    getOnlineModels()
  File "D:\Lockbox\Others\MFCRecorder-master/getModels.py", line 56, in getOnlineModels
    with open('models.pickle', 'wb') as handle:
PermissionError: [Errno 13] Permission denied: 'models.pickle'

Which might cause issues later

**Comment by beaston02** [comment]
Great to hear!!! Thank you again. 

The permission error should stop the script from working (it wont see which models are online and as a result, wont start recording any models). 

If that issue comes up again, Ill now know how to help them! 

Im going to go ahead and close this issue. Thank you agin. If there is anything else, please let me know! 

Ill hopefully have an update before too long with a much cleaner view of the information and statistics, and more user friendly.
