### ISSUE TITLE
A few improvements for new_script

### ISSUE THREAD

**Issue by David-Eilers** [beaston02/MFCRecorder#27]
hi @sKanoodle,

I've been following your development of the new script and i like what your doing, i found some mayor oversights though.

1. The way of setting min viewers in `keep_recording` in `classes/config.py`
2. Tag-based matching doesn't exist in `keep_recording` thus triggering the else statement and causing errors
3. i presume blacklist checking is broken so `keep_recording` keeps returning a `False` boolean value 

During debugging i dealt with these issues the following way

1. 
	* Set `session['uid']` to a local `uid` variable inside `keep_recording` 
	* Set `min_viewers` the following way:

* The old way was:
```python
min_viewers = self.filter.auto_stop_viewers if session['condition'] == 'VIEWERS_' else self.filter.wanted.dict[session['uid']['stop_viewers']]
```
* My new way
```python
else:
    min_viewers = self.filter.wanted.dict[uid]['stop_viewers']
```
* The whole if statement:
```python
uid = session['uid']

if session['condition'] == 'VIEWERS_':
    min_viewers = self.filter.auto_stop_viewers
elif "(" in session['condition']:
    min_viewers = self.filter.auto_stop_viewers
else:
    min_viewers = self.filter.wanted.dict[uid]['stop_viewers']
```
2. This is very crude and should probably be replaced with something more clever
	* check for a `"("` inside `session['condition']` to indicate tag-based recording
```python
elif "(" in session['condition']:
    min_viewers = self.filter.auto_stop_viewers
```
3.
	* Replace the one-line Return-statement with an easier to understand if-statement
	
* The old way:
```python
return (session['rc'] >= min_viewers
        and self._available_space > self.settings.min_space
        #TODO: should we really instantaneously stop recording if model was added to blacklist??
        and self.filter.wanted.is_blacklisted(session['uid']))
```
* My new way:
```python
if session['rc'] >= min_viewers and self._available_space > self.settings.min_space:
    return True
else:
    return False
```

NOTE: I removed the blacklist check because i couldnt find out how it worked and should probably be added back.

With these changes recording based on wanted, viewers or tags works without any errors.

I could submit a pull request but i think it is easier for you to implement these changes than it is for me to cleanup my messy code

**Comment by sKanoodle** [comment]
@David-Eilers thanks for your effort in testing this.

1.  I think the problem here was a bracket. `self.filter.wanted.dict[session['uid']['stop_viewers']]` should have been `self.filter.wanted.dict[session['uid']]['stop_viewers'] `. Nevertheless, the way of getting the min_viewers was flawed as mentioned in the comment in the code. It would also stop recording when the starting condition was, for example, tags. Which brings us straight to point 2.

2. I think even better than your approach would be setting the min_viewers to 0 if the recording wasn't started by auto recording min viewers (`condition == 'VIEWERS_'`) or by the model being wanted (`condtition == ''`)

3. Blacklist checking returns correct values, it was only the usage that was wrong. It should have been `and not self.filter.wanted.is_blacklisted(session['uid'])`. I now removed blacklist checking there altogether, since it doesn't feel right. Blacklist checking is for starting recordings, not to interrupt them, in my opinion.

Please let me know if these changes fix the problems you discovered.

**Comment by David-Eilers** [comment]
All the problems i have mentioned seem to be fixed. good job!
