### ISSUE TITLE
Working on Win10 with Python3.5.2

### ISSUE THREAD

**Issue by SearchAndDestroy** [beaston02/MFCRecorder#3]
Not really an issue but I just cloned the repro on my Win 10 machine and it seems to work great. I will check the recordings but the models were recorded.
Will you add an option for the format of the directory and filename?
Also can I have the wanted.txt file in a mounted network drive form my Synology NAS (i.e. V:/Bla/wanted.txt) ?

You can easily get the ID from the url when you send a tip. It's http://www.myfreecams.com/php/tip.php?request=tip&broadcaster_id=20642838&cache_id=1501113506&night_mode=1 so broadcaster_id is the number you want.

**Comment by beaston02** [comment]
I will add the custom path format. I have that as an option on the ChaturbateRecorder script, so I'll do the same here unless you have other input on how it might be done...? (It won't have the "{gender}" tag since all models on MFC are female of course). 

I have not tested with the wanted.txt being on a network drive, but it does not require it to be in the location as the script, so as long as the drive is mounted, I don't see why it wouldn't work. Another option may be (I have not tested this) to have a  symlink to the file (shortcut I believe is what this is called in windows), and set the path to the symlinked file in the config. Have you tested it and it's not working, or just asking if it is ok to be done that way? I do not have a windows machine to test on myself. 

There are a number of ways to get the broadcasters ID. I explained the profile image way in the readme because I figured it would be the easiest. I want to add a way to add the model by their current display name to the script, but because of how I currently have the info being logged to the screen, I haven't found a decent way to go about it (if you type "add modelname" thr cursor keeps moving and printing over as you type). I've also thought about having a different script for adding the model, but again, I just haven't been happy enough with anything I've came up with at this point. I may even add an api to the script, run it as a web server, and create a greasemonkey/tampermonkey script to simply click a button on the users profile or chat room to add them, if I go that route, it won't be a while until I get it done. 

I am certainly open for input, but I still consider myself to very much be learning Python, so don't expect too much from me! ;)

**Comment by beaston02** [comment]
I just updated the script allowing for a custom directory structure, and file name. Here is a quick rundown which is included in the new config.conf file.

> {path} = save_directory set above. (your directory structure should start with this)
 {model} = the models name
 {uid} = models uid or broadcaster id. This is a number which is always consistent. The models name can be changed, so this is what I find best for keeping all videos of a model in the same directory
 "{year}, {month}, {day}, {hour}, {minutes}, {seconds}" should all be easy enough to figure out what these are
 you can also change ".mp4" to another extension. ".ts" is what the stream is actual broadcast as.
 example using a madeup "hannah" who has the uid 208562: {path}/{uid}/{year}/{year}.{month}.{day}_{hour}.{minutes}.{seconds}_{model}.mp4 = "/Users/Joe/MFC/208562/2017/2017.07.26_19.34.47_hannah.mp4"

I also added the option to run a post processing script on the files once they are completed. 

Although its not a huge deal, I will mention that you can choose an issue "type" (or whatever its called on here) when submitting an issue. The default is an "issue" which generally means a problem, but you can change it to "enhancement" (among other things) which would be more fitting for a feature request. Again, not really any trouble, but I just thought I would mention it for your own knowledge :) 

Please let me know if you have any other requests or any problems!
