### ISSUE TITLE
Can't install opencv-python on arm

### ISSUE THREAD

**Issue by pokbb** [beaston02/MFCRecorder#30]
First, thanks for this amazing script.
I'm running this script since some months ago, but today I update to the new version and i cant run the script. The script need cv2 class but opencv-python isn't compatible with arm:

https://github.com/skvark/opencv-python/issues/13

Is there a possibility of change this class in the script for another?
Thanks.
P.S. English not my mather lenguage, I'm sorry my english xD
P.S.2: I use raspberry pi

**Comment by David-Eilers** [comment]
A quick google search shows that there seems to be a way to install opencv on raspberry pi, so maybe do some more research and maybe you will get it working after all.

Otherwise maybe the code could be changed to use ffmpeg or something like it instead of opencv, but i personally dont have the time to take a look at it right now.

**Comment by sKanoodle** [comment]
@pokbb opencv-python is something I experimented with, but it didn't even end up used for creating the thumbnails in the webapp. I removed it as a requirement now, so there is no need to install it at all anymore.

**Comment by pokbb** [comment]
@David-Eilers 
Oh, sorry, my mistake. I see some tutorials, but unfortunately I can't install it.

@sKanoodle 
I don't use the web app, for record four models, i dont need it xD
Thanks, now work perfect.
