### ISSUE TITLE
Enhancement: Download based on room viewer numbers

### ISSUE THREAD

**Issue by Gimpoid** [beaston02/MFCRecorder#5]
Not really an issue more an enhancement just wondering if it would be possible to enable downloads of rooms when they reach a certain threshold of users. For example if a room hits 1000+ viewers I would assume something interesting is going on there so it would be useful for the script to automatically start recording that session for me even if its not a model in my wanted list.

This could also possibly be useful with models in the wanted list if you only wanted to start recording once a room reaches a certain number of viewers say 100 as if its below that number from experience you know not much is going on that's interesting.

Perhaps another option would be an optional variable in the wanted list where you have the model number then a comma separator and then the number of viewers before it triggers recording (leave blank to record with any number like the current function). This way you can set up thresholds on a per model basis and leave the record any model above 1000 viewers setting in the current config file.

**Comment by beaston02** [comment]
I just added some settings to the config file. I did not add a model specific setting for minimum viewers (yet) but I did add a general minimum viewer setting. I may add the model specific later when I have more time. 

I added options for auto recording models who are not in the wanted list based on the following:
number of viewers in the room
the models camscore
and new models (based on a configurable number of hours since they signed up as a model).

The minimum number of viewers will still apply to these options. 

I also added a blacklist file to add models UIDs to if you dont want to record them regardless of them meeting the AutoRecord options. 

I also think I need to move all the notes from the config.conf file to the readme, or some other file as it is getting very cluttered... but that will have to be another time. 

Im going leave this request open, and if you are happy with these changes, feel free to close it. Otherwise, let me know what you would like to see changed.

**Comment by Gimpoid** [comment]
Thats great thanks! I will test it out and let you know. I like the blacklist and the new models options too!

One thing I did think of was is it possible to have a number of viewers to stop recording also for the models not on the wishlist. e.g. I set it to start recording at 1000 viewers as I assume it would be a public show or something special to drag in that number and I set it to stop recording when it hits say 500 viewers as the show has most likely ended by then.

**Comment by beaston02** [comment]
Auto stopping was something I had thought about but wasn't something I was aware of how to do right off the top of my head (I still consider myself new to Python). Im heading out of town early tomorrow morning, and probably will not have a chance to look into it before then. I'll plan to look into it when I get back in town and see if I can't figure something out.

**Comment by beaston02** [comment]
I added a "stopViewers" setting in the config. If a room drops below this number, the recording will stop. 

I recommend a fair difference between the two numbers so it doesnt keep fluctuating between the two, causing short sessions to be recorded. For example, if they are a difference of 5, all it takes is 5 users to logout, and the video will stop recording, then 5 more users to join and the video could start recording again. this could easily happen within the time of a single check. 

I will probably change this to require the number to be below the value for a certain amount of time prior to ending the recording to avoid this, but for now, this is how it works.

**Comment by Gimpoid** [comment]
Thanks I will test it out later today when I have some free time.

So it only stops recording the models not in the wanted list right?

Currently I have it start at about 1000 viewers as that usually means something interesting has occurred like a public show of a model I haven't noticed or yesterday there was a new model from Twitch or YouTube with 20,000+ viewers which it caught and I wouldn't have known about which was great.

I think setting it to stop when it drops to 500 or less should signal the end of the public show when people all flood out of the room? This should stop me recording 2 or more hours where the model just sits around talking, for the ones not on the wanted list where I would only want to see some boobs etc haha. Currently most of the time it will only record those models for 20-30 minutes because they do the public show right at the end of the session and then log out, if they come back later they wont have 1000 viewers so it wont record them anymore which works well to limit file sizes 👍

**Comment by beaston02** [comment]
I coded it for all models (wanted and those meeting the auto record conditions). I thought thats what you were asking for. I will make some changes and update it

**Comment by beaston02** [comment]
I changed the "stopViewers" under settings to only deal with models on the wanted list, so if the number of viewers in a models room drops below this number, the recording will stop. This will work in conjunction with the "minViewers" (also under settings).

I added "autoStopViewers" under the "AutoRecording" section which will only apply to models who are not on the wanted list, and grabbed based on the "viewers" under the "AutoRecording" section of the config file.

**Comment by Gimpoid** [comment]
That's great thanks Ill test it out =)

**Comment by beaston02** [comment]
Since this has been the thread for auto recording settings, I figured I would post this here.

I just added the option to record models based on their tags also. 

You can set a list of tags (separated by commas), and a number of minimum tags from the list which must be matched. 

If your set list is "tag1, tag2, tag3, tag4, tag5, tag6"

and you have minTags set to "4":

`"tag2, tag4, tag12, tag5, tag10, tag7"` would not start - tag2, tag4, tag5 is only 3 matched. 

`"tag2, tag4, tag12, tag5, tag10, tag1, tag11"` would start - tag2, tag4, tag5, tag1 >= minTags

The general minimum viewers setting (stopViewers) will still apply.

**Comment by beaston02** [comment]
Im going to close this. If you have anymore feature requests, please open a new issue.

Thank you!
